import { Logger } from './Logger';
import { EnhancedEventEmitter } from './enhancedEvents';
import * as utils from './utils';
import * as ortc from './ortc';
import { ConsumerImpl } from './Consumer';
import type { Consumer, ConsumerType, ConsumerLayers } from './ConsumerTypes';
import type { AppData } from './types';
import type { RtpCapabilities } from './rtpParametersTypes';
import { TransportImpl, TransportConstructorOptions } from './Transport';
import type {
	TransportListenIp,
	TransportTuple,
	TransportTraceEventData,
	TransportEvents,
	TransportObserver,
} from './TransportTypes';
import * as FbsRequest from './fbs/request';
import * as FbsTransport from './fbs/transport';


export type ShmTransportOptions<ShmTransportAppData extends AppData = AppData> =
{
  /**
   * Listening IP address.
   */
  listenIp: TransportListenIp | string;

	/**
	 * Shm file name
	 */
  shm: string;

  log?: string;

  /**
   * Custom application data.
   */
  appData?: ShmTransportAppData;
}

const logger = new Logger('ShmTransport');

export interface ShmTransportStat
{
  // Common to all Transports.
	type: string;
	transportId: string;
	timestamp: number;
	bytesReceived: number;
	recvBitrate: number;
	bytesSent: number;
	sendBitrate: number;
	rtpBytesReceived: number;
	rtpRecvBitrate: number;
	rtpBytesSent: number;
	rtpSendBitrate: number;
	rtxBytesReceived: number;
	rtxRecvBitrate: number;
	rtxBytesSent: number;
	rtxSendBitrate: number;
	probationBytesReceived: number;
	probationRecvBitrate: number;
	probationBytesSent: number;
	probationSendBitrate: number;
	availableOutgoingBitrate?: number;
	availableIncomingBitrate?: number;
  maxIncomingBitrate?: number;
  //ShmTrtansport specific
  shm: string;    // shm file name
  writer: number; // writer status: initialized, closed, undefined
}

export type ShmConsumerOptions<ConsumerAppData> =
{
	/**
	 * The id of the Producer to consume.
	 */
	producerId: string;

	/**
	 * RTP capabilities of the consuming endpoint.
	 */
	rtpCapabilities: RtpCapabilities;


	paused?: boolean;

	/**
	* The MID for the Consumer. If not specified, a sequentially growing
	* number will be assigned.
	*/
	mid?: string;

	/**
	 * Preferred spatial and temporal layer for simulcast or SVC media sources.
	 * If unset, the highest ones are selected.
	 */
	preferredLayers?: ConsumerLayers;

	ignoreDtx?: boolean;

	/**
	 * Whether this Consumer should consume all RTP streams generated by the
	 * Producer.
	 */
	pipe?: boolean;

	/**
	 * Custom application data.
	 */
	appData?: ConsumerAppData;
}

export type ShmTransportEvents = TransportEvents;

export type ShmTransportObserver = TransportObserver;

export type ShmTransportData =
{
	shm: {
		name?: string;
		log?: string;
	}
};

type ShmTransportConstructorOptions<ShmTransportAppData> =
	TransportConstructorOptions<ShmTransportAppData> &
	{
		data: ShmTransportData;
	}

export class ShmTransport<ShmTransportAppData extends AppData = AppData>
 extends TransportImpl<ShmTransportAppData, ShmTransportEvents, ShmTransportObserver>
{
	//ShmTransport data: shm and log
	readonly #data: ShmTransportData;

	// Next MID for Consumers. It's converted into string when used.
	#nextMidForConsumers = 0;
	
	/**
	* @private
	 *
	 */
	constructor(options: ShmTransportConstructorOptions<ShmTransportAppData>)
	{
		const observer = new EnhancedEventEmitter();
		super(options, observer as ShmTransportObserver);

		logger.debug('constructor()');

		const { data } = options;

		this.#data = data;
	}

	get type(): 'webrtc' | 'plain' | 'pipe' | 'direct' {
		return 'pipe'; // ShmTransport acts like a pipe transport
	}

	async dump(): Promise<any> {
		logger.debug('dump()');
		// Return basic dump info - can be extended as needed
		return {
			id: this.id,
			// Add other relevant dump data
		};
	}


	/**
	 * Close the ShmTransport.
	 *
	 * @override
	 */
	override close(): void
	{
		if (this.closed)
			return;

		super.close();
	}

	/**
	 * Router was closed.
	 *
	 * @private
	 * @override
	 */
	override routerClosed(): void
	{
		if (this.closed)
			return;

		super.routerClosed();
	}

	/**
	 * Get ShmTransport stats.
	 *
	 * @override
	 */
	override async getStats(): Promise<ShmTransportStat[]>
	{
		logger.debug('ShmTransport.getStats()');

		// Note: This needs to be updated to use the new FlatBuffers API
		// For now, returning a basic structure
		return [] as ShmTransportStat[];
	}

	/**
	 * Provide the ShmTransport remote parameters.
	 *
	 * @param {String} shm- shm name.
	 *
	 * @async
	 * @override
	 */
	override async connect(
    params: {
      shm: string
    }): Promise<void>
	{
		logger.debug('ShmTransport.connect()');

		// Note: This needs to be updated to use the new FlatBuffers API
		// For now, this is a placeholder
		// The actual implementation would use channel.request with proper FlatBuffers encoding
	}

	/**
	 * Create a shm Consumer.
	 *
	 * @virtual
	 */
	override async consume<ConsumerAppData extends AppData = AppData>(
		{
			producerId,
			rtpCapabilities,
			paused = false,
			mid,
			preferredLayers,
			ignoreDtx = false,
			pipe = false,
			appData
		}: ShmConsumerOptions<ConsumerAppData>
	): Promise<Consumer<ConsumerAppData>>
	{
		logger.debug('consume()');

		if (!producerId || typeof producerId !== 'string')
			throw new TypeError('missing producerId');

		else if (appData && typeof appData !== 'object')
			throw new TypeError('if given, appData must be an object');

		else if (mid && (typeof mid !== 'string' || mid.length === 0))
			throw new TypeError('if given, mid must be non empty string');

		// This may throw.
		ortc.validateRtpCapabilities(rtpCapabilities!);

		const producer = this.getProducerById(producerId);
		if (!producer)
			throw Error(`Producer with id "${producerId}" not found`);

		// This may throw.
		const rtpParameters = ortc.getConsumerRtpParameters(
			{
				consumableRtpParameters : producer.consumableRtpParameters,
				remoteRtpCapabilities   : rtpCapabilities!,
				pipe,
				enableRtx : false
			});

		// Set MID.
		if (!pipe)
		{
			if (mid)
			{
				rtpParameters.mid = mid;
			}
			else
			{
				rtpParameters.mid = `${this.#nextMidForConsumers++}`;

				// We use up to 8 bytes for MID (string).
				if (this.#nextMidForConsumers === 100000000)
				{
					logger.error(
						`consume() | reaching max MID value "${this.#nextMidForConsumers}"`);

					this.#nextMidForConsumers = 0;
				}
			}
		}

		const consumerId = utils.generateUUIDv4();
		const shmData = appData ?
			{
				shm: (appData['shm'] !== undefined) ? appData['shm'] : {},
				log: (appData['log'] !== undefined) ? appData['log'] : {}
			}
			: {};

		// Note: This needs to be updated to use the new FlatBuffers API
		// For now, create a consumer using the parent class's implementation
		// but with shm-specific type
		const data =
		{
			producerId,
			kind : producer.kind,
			rtpParameters,
			type : 'pipe' as ConsumerType  // Use 'pipe' since 'shm' is not in standard types
		};

		const consumer = new ConsumerImpl<ConsumerAppData>({
			internal: {
				...this.internal,
				consumerId
			},
			data,
			channel: this.channel,
			appData,
			paused: paused,
			producerPaused: false,
			score: { score: 10, producerScore: 10, producerScores: [] },
			preferredLayers: preferredLayers
		});

		this.consumers.set(consumer.id, consumer);
		consumer.on('@close', () => this.consumers.delete(consumer.id));
		consumer.on('@producerclose', () => this.consumers.delete(consumer.id));

		// Emit observer event.
		this.observer.safeEmit('newconsumer', consumer);

		return consumer;
	}

	/**
	 * Write stream metadata to the SHM transport.
	 *
	 * @param {Object} params - Parameters containing metadata.
	 * @param {string} params.meta - The metadata string to write.
	 *
	 * @async
	 *
	 * @remarks
	 * This is a Lively-specific custom method for SHM transports that writes
	 * metadata to the shared memory stream.
	 *
	 * The C++ worker (RTC::ShmTransport) processes this via FlatBuffers and
	 * calls WriteStreamMeta on the SHM context.
	 */
	async writeStreamMetaData(
		{
      meta
    }:
    {
      meta: string;
    }): Promise<void>
	{
		logger.debug('writeStreamMetaData()');

		// Build FlatBuffers request
		const metaOffset = this.channel.bufferBuilder.createString(meta);
		const shmOffset = this.channel.bufferBuilder.createString(this.#data.shm.name || '');

		const requestOffset = FbsTransport.ConsumeStreamMetaRequest.createConsumeStreamMetaRequest(
			this.channel.bufferBuilder,
			metaOffset,
			shmOffset
		);

		await this.channel.request(
			FbsRequest.Method.TRANSPORT_CONSUME_STREAM_META,
			FbsRequest.Body.Transport_ConsumeStreamMetaRequest,
			requestOffset,
			this.internal.transportId
		);
	}

	/**
	 * Does nothing, should not be called like this
	 *
	 * @private
	 * @override
	 */
	private handleWorkerNotifications(): void
	{
		this.channel.on(this.internal.transportId, async (event: string, _data?: any) => {
			switch (event)
			{
				default:
				{
					logger.error(`ignoring unknown event "${event}"`);
				}
			}
		});
	}
}
